### ISSUE TITLE
CKR_FUNCTION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by nhgs64** [Azure/iot-identity-service#162]
Hello,

I'm trying to set up a TPM-based device identity using EST but am having trouble with the keyd service.

> Mar 17 13:33:54 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:54Z [INFO] - Starting server...
> Mar 17 13:33:54 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:54Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
> Mar 17 13:33:54 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:54Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (56 bytes)
> Mar 17 13:33:54 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:54Z [INFO] - <-- POST /keypair?api-version=2020-09-01 {"content-type": "application/json", "ho st": "foo", "content-length": "56"}
> Mar 17 13:33:54 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:54Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [ERR!] - could not generate key pair: C_GenerateKey failed with CKR_FUNCTION_NOT_SUPPORTED
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [ERR!] - !!! internal error
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [ERR!] - !!! caused by: could not generate key
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [ERR!] - !!! caused by: could not create key: AZIOT_KEYS_RC_ERR_EXTERNAL
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [INFO] - --> 500 {"content-type": "application/json"}
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [DBUG] - [hyper::proto::h1::io] flushed 155 bytes
> Mar 17 13:33:58 raspberrypi aziot-keyd[5191]: 2021-03-17T17:33:58Z [DBUG] - [hyper::proto::h1::conn] read eof

Any idea what would cause the "CKR_FUNCTION_NOT_SUPPORTED" error? I've created the keystore and keys as user aziotks so hopefully not a permissions issue. Reported keyd version is 1.2.0 rc4.

**Comment by arsing** [comment]
tpm2-pkcs11 doesn't implement `C_GenerateKey` and returns `CKR_FUNCTION_NOT_SUPPORTED`

Supporting PKCS#11 implementations like tpm2-pkcs11 which don't implement `C_GenerateKey` (by falling back to filesystem keys) was done in 1cf428fe92104651668494be0c8e9def431e0550 . It was committed after rc4, so it'll be in 1.2.0 proper. If you want to test now you can pick up a master package from our CI.
