### ISSUE TITLE
Is the PUT /identities/modules/{module-id} API necessary?

### ISSUE THREAD

**Issue by micahl** [Azure/iot-identity-service#236]
Opening this to track whether the API is required for something and if so to document what that is.  It currently isn't included in the openapi spec for IS.  Otherwise, we should remove it from docs and code.

**Comment by gordonwang0** [comment]
Per @varunpuranik, this API is used in edged to update the credentials of EdgeAgent and EdgeHub, which are created by default with noauth.

So we need to keep this API and add it to the openapi spec.

**Comment by varunpuranik** [comment]
Yes, that is correct. It is basically used for scenarios where there is a deployment and the module identity already exists - in that case we update the creds of the module so that we know the SAS key used for the module.

**Comment by gordonwang0** [comment]
Closing this; we determined this API is necessary.
