### ISSUE TITLE
Certificates are only renewed at exact expiration date

### ISSUE THREAD

**Issue by maksokami** [Azure/iot-identity-service#300]
Right now in 1.2.3 certificate renewal will only happen once at the expiration. Source: [aziot-identityd - identity.rs](https://github.com/Azure/iot-identity-service/blob/9a12cd33ef27f82a5524c0d0d58938ec797fa852/identity/aziot-identityd/src/identity.rs#L828).  
This is not practical at all for IIoT devices that are often deployed in places with unreliable connectivity. With such approach renewal is likely to fail, while automatic renewal is also a key feature many customers were waiting for.  

A much better approach would be to start repeated attempts to renew, when certificate is about 80-90% expired. Then, if first renewal attempt failed, next one can be scheduled in X weeks/x days, and the closer the expiration date the more frequent attempts should be. If this will not be the default behavior, at least there should be an option to enable it.

**Comment by ondrejspilka** [comment]
We're just discussing the same, would be super to have option to setup tolerance in days for renewal. 
Curious question - when x509 is issued by EST, does IoT Edge still need user/password to EST for renewal of the certs or is it using existing issued certificate to authenticate renewal?

**Comment by arsing** [comment]
cc @gordonwang0 @onalante-msft

**Comment by gordonwang0** [comment]
We have implemented a configurable auto-renewal of the device ID and EST identity certs.

The option is available here for device identity certs:
https://github.com/Azure/iot-identity-service/blob/e5a0e0bd98c5aadb9fc8b6830e45203fcd9f232d/aziotctl/config/unix/template.toml#L132-L134

And here for EST identity certs:
https://github.com/Azure/iot-identity-service/blob/e5a0e0bd98c5aadb9fc8b6830e45203fcd9f232d/aziotctl/config/unix/template.toml#L182-L184

Note that this feature isn't released yet and will go in a future release. However, you can try it out now by downloading the latest packages from this repo.
