### ISSUE TITLE
Error using AEAD encryption

### ISSUE THREAD

**Issue by vslepakov** [Azure/iot-identity-service#312]
Using [this endpoint](https://azure.github.io/iot-identity-service/api/keys-service.html#aead) for encryption with AEAD results in the following error in the logs:

> Nov 10 15:09:20 iotedge12 aziot-keyd[13557]: 2021-11-10T15:09:20Z [ERR!] - error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length:../crypto/evp/evp_enc.
Nov 10 15:09:20 iotedge12 aziot-keyd[13557]: 2021-11-10T15:09:20Z [ERR!] - !!! internal error
Nov 10 15:09:20 iotedge12 aziot-keyd[13557]: 2021-11-10T15:09:20Z [ERR!] - !!! caused by: could not encrypt
Nov 10 15:09:20 iotedge12 aziot-keyd[13557]: 2021-11-10T15:09:20Z [ERR!] - !!! caused by: could not encrypt: AZIOT_KEYS_RC_ERR_EXTERNAL

The API returns an internal server error.

**Comment by vslepakov** [comment]
any updates on this?

**Comment by arsing** [comment]
Well, you haven't given us any information. Obviously the API works fine; edged uses it just fine. So rather than just pasting the logs you need to give us an actual repro.

**Comment by vslepakov** [comment]
I found the issue while re-constructing the repro...I used the wrong method to generate the key. Thanks
