### ISSUE TITLE
Release Tag 1.2.4

### ISSUE THREAD

**Issue by elrosar** [Azure/iot-identity-service#328]
Hi,

I am using the sources from Github to build an RPM for openSUSE MicroOS. I know the distribution is not officially supported but it is no option for me to switch to another distro. Since a few days I get a warning when running `iotedge check` saying that I should update to `1.2.4`. The warning explicitly says:

```
...
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.2.3 but 1.2.4 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
...
```

I really would like to update my RPM version to `1.2.4` but there is no corresponding tag in this repository. I am checking out the Git repo at a specific release tag (i.e. `1.2.3` currently) and would prefer to stay on a release tag instead of figuring out a commit hash that may (or may not) corresponds to `1.2.4`. Would you mind adding a tag for release `1.2.4`?

**Comment by arsing** [comment]
[Done.](https://github.com/Azure/iot-identity-service/releases/tag/1.2.4)
