### ISSUE TITLE
EST basic authentication doesn't allow empty username

### ISSUE THREAD

**Issue by ondrejspilka** [Azure/iot-identity-service#333]
When `username` is omitted from EST **Basic** authentication, **colon** is still added.
**Digicert** is one of the providers supporting just passcode passed in password field, **but without colon**. Configuring colon is plaintext passcode is challenging.

> (even though we can challenge this decision, since omitting username is not covered by [RFC2617 Basic authentication scheme](https://datatracker.ietf.org/doc/html/rfc2617#page-5). **Unfortunately Digicert is not willing to change the behavior to conform RFC2617.**

Solution to that is to slightly modify **aziot-certd**, file `/src/est.rs` r.g. in following way:

![image](https://user-images.githubusercontent.com/3624673/144367995-13c888be-b414-4b47-a9a1-cc99c86c1318.png)

It doesn't hurt anything, I would say small sacrifice compared extended options of IoT Edge with respect to Digicert.

Should I create PR?

**Comment by arsing** [comment]
>Unfortunately Digicert is not willing to change the behavior to conform RFC2617.

We had heard they would change.

cc @onalante-msft @eustacea to confirm.

**Comment by ondrejspilka** [comment]
Do you mean Digicert? I wonder, yesterday I've got feedback they won't...

**Comment by onalante-msft** [comment]
I have been successfully using basic authentication with the colon.  I will check if anything has changed on our instance.

**Comment by ondrejspilka** [comment]
Closing as this is supported.
