### ISSUE TITLE
Broken build on NixOS

### ISSUE THREAD

**Issue by onalante-msft** [Azure/iot-identity-service#352]
Issues, in order, expanding as found:
- `Makefile` refers to `/bin/bash`, but bash does not exist at this path on NixOS.
- NixOS sets `_FORTIFY_SOURCE=2` by default (~~investigating why~~ https://github.com/NixOS/nixpkgs/issues/18995). However, `openssl-sys2` sets `-O0`, and so a warning will be emitted that `_FORTIFY_SOURCE` will not be respected. Debian glibc has a patch suppressing this warning, and moreover does not have gcc set `_FORTIFY_SOURCE` by default.

**Comment by arsing** [comment]
>* `Makefile` refers to `/bin/bash`, but bash does not exist at this path on NixOS.

`make SHELL=... ...` ?

>However, `openssl-sys2` sets `-O0`

To be clearn this is only when compiling a debug build with `cargo build`, yes? Or does it also happen in release builds? The `cc::Build` created by `openssl_build::get_c_compiler()` should default to an opt level based on the cargo target automatically.

**Comment by onalante-msft** [comment]
> `make SHELL=... ...` ?

Exactly.

> To be clear, this is only when compiling a debug build with cargo build, yes? Or does it also happen in release builds? The cc::Build created by openssl_build::get_c_compiler() should default to an opt level based on the cargo target automatically.

Yes, I believe release defaults to `O3` unless otherwise requested.
