### ISSUE TITLE
Debian postrm script fails to execute purge command when run inside systemd-nspawn container

### ISSUE THREAD

**Issue by msqr** [Azure/iot-identity-service#531]
The Debian package script fails to execute when run inside a `systemd-nspawn` container. It fails here:

https://github.com/Azure/iot-identity-service/blob/7aa53d0443eefb910954df1a8ef124170cfb73c3/contrib/debian/postrm#L23

This is a similar problem as Azure/iotedge#7027. Switching to something like

```sh
systemctl daemon-reload 2>/dev/null || true
```

fixes the issue.

**Comment by arsing** [comment]
Yes, I don't see any problem with ignoring a failure from `daemon-reload`. I do wonder if we need it at all, or if the default control script would've already called it for us before this point.
