### ISSUE TITLE
Long timeout before fallback to backup, and inconsistent backup usage - leads to failing IoT Edge Modules when device is offline.

### ISSUE THREAD

**Issue by jakhog** [Azure/iot-identity-service#542]
We are currently having some issues with iotedge 1.4.9 + aziot 1.4.3 in poor connectivity scenarios.

Our devices frequently have to operate in poor connectivity environments, meaning high packet loss and long round-trip times. After upgrading from iotedge 1.1 to 1.4, we have started experiencing issues where the modules are not able to connect to the EdgeHub - which means the solution stops working.

This seems to be caused by a combination of "issues", some of them could be improved in the __identityd__ service. We have seen the following things causing issues in our situation:

### 1. Too long timeouts combined with serving backups only after failure
https://github.com/Azure/iot-identity-service/blob/33825efda701ae451cf6bb5e0f8b92f924c42acd/identity/aziot-identityd/src/identity.rs#L284-L375

This method, together with the minimum timeout of 70 seconds (and default 1 retry):
https://github.com/Azure/iot-identity-service/blob/33825efda701ae451cf6bb5e0f8b92f924c42acd/identity/aziot-identityd-config/src/lib.rs#L86

Leads - eventually - to our ModuleClients timing out while connecting. After a little while, they will reconnect - and time out again. They never receive the backup which is stored locally because the timeout is too long.

### 2. The backups are not used when listing module identities
https://github.com/Azure/iot-identity-service/blob/33825efda701ae451cf6bb5e0f8b92f924c42acd/identity/aziot-identityd/src/identity.rs#L377-L426

In contrast to the aforementioned method, this method does not fall back to the locally stored backups if the cloud connection times out. The EdgeAgent uses this `GetIdentities` call as an optimisation instead of `GetIdentity` if it has to re-create a deleted module container. Since it gets an empty set of identities when offline - it fails.

### 3. Requests to the service is queued
Related to 1. - it appears like the requests are queued by __identityd__, so that if multiple of our modules try to connect to the EdgeHub at the same time, they will all fail after having waited for the first `GetIdentity` call timing out.

## Suggestions/Ideas
I don't know all the implications of these changes, but from our perspective - we believe that the following changes would help our current issues:

- Allowing us to configure a shorter `cloud_timeout_sec`, would mean that backups are served before the ModuleClient times out. If we could configure the "queuing" on __identityd__ (if there is any), that would also help.
- Serving the last received (backup) identities immediately if available, and fetching new ones in the background. Since the backup is already there, after the first fetch - that would speed up the offline "booting" process a great deal, and mean that data collecting services have less downtime.

Is any of this doable? Please let me know if you need more details...

**Comment by arsing** [comment]
>This method, together with the minimum timeout of 70 seconds (and default 1 retry):

IIRC the 70s minimum is because IoT Hub's SLA is that there can be up to 60s delay for a response, so they expect clients to use a timeout slightly higher than that.

>In contrast to the aforementioned method, this method does not fall back to the locally stored backups if the cloud connection times out.

That should be fixed if so.

>Requests to the service is queued

identityd handling only one request at a time is "intentional" in that all the services were written to not be complicated about concurrent requests, stale data, etc. Every request just takes a lock and does its thing.

>- Serving the last received (backup) identities immediately if available, and fetching new ones in the background.

This might be doable.

**Comment by jakhog** [comment]
Wow - thanks a lot for the great answers, and super quick patching! 👏  We have just built a new version from main and will be testing it out right now. From the changes, it looks exactly like what we wanted it to do - but will confirm as soon as I have more evidence 👍

**Comment by jakhog** [comment]
From our running tests with a local build, this is looking very promising. The modules can connect to EdgeHub very fast even without IoThub connection 👏 At what time do you think it would be possible to release these fixes as an official version?

**Comment by arsing** [comment]
[v1.4.20](https://github.com/Azure/azure-iotedge/releases/tag/1.4.20) has been released.
