### ISSUE TITLE
error: first is not defined

### ISSUE THREAD

**Issue by Ming-Y-ANG** [Azure/iot-identity-service#548]
When I cross-compile the package by docker, the following error appears in third-party-notices.sh：
` declare -A dependencies
for crate_name in ''\''aziotctl'\''' ''\''aziot-certd'\''' ''\''aziot-identityd'\''' ''\''aziot-keyd'\''' ''\''aziot-keys'\''' ''\''aziot-tpmd'\'''
 jq -r --arg crate_name aziotctl '
                map(select(.id | startswith("\($crate_name) "))) |
                first |
                .id
            '
error: first is not defined
                first |                1 compile error
crate_pkg_id=
Makefile:264: recipe for target 'dist' failed
`
I didn't find the relevant tools(first) through apt，docker bash version is：
`GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)`
Can anyone help me solve this problem?

**Comment by arsing** [comment]
Whatever distro you're compiling in has a `jq` that's too old. Specifically `first` was introduced in v1.5. All the distros listed in https://github.com/Azure/iot-identity-service/blob/main/docs-dev/packages.md will work, so I assume you're using an even older one.

**Comment by Ming-Y-ANG** [comment]
Yes, I use the debian 8 docker image because I need to install the package on the embedded device. Due to the limitation of the c library version, I cannot use the new version of the image. I will try to upgrade jq.
Finally, thank you very much for your answer

**Comment by arsing** [comment]
Note that you're likely to have more problems with Debian 8 than just an old jq. We only support Debian 10+ officially.
