### ISSUE TITLE
fatal: not a git repository: /root/iot-identity-service/.git/modules/third-party/libtpms

### ISSUE THREAD

**Issue by Ming-Y-ANG** [Azure/iot-identity-service#550]
The following problems occurred when I used debian10 docker image to cross-compile arm32v7:

![image](https://github.com/Azure/iot-identity-service/assets/48575506/eec9a020-481e-4737-8ae9-9d208491d6ce)
This is my compile script:

![image](https://github.com/Azure/iot-identity-service/assets/48575506/708c157c-111f-46db-a0f6-18d080c87eac)

Did I miss something?

**Comment by arsing** [comment]
You didn't clone submodules.

**Comment by Ming-Y-ANG** [comment]
I have previously used the following command to update the sub-repository, but it seems to have no effect：

![image](https://github.com/Azure/iot-identity-service/assets/48575506/bc118760-8b96-4f79-bad8-dd6c93c309b9)

**Comment by arsing** [comment]
Make sure your root repository or any of the submodules don't have untracked changes. Worst case make a new clone with `git clone --recursive` so that submodules are cloned from the start.

**Comment by Ming-Y-ANG** [comment]
I found that my sub-repository is in detached state. What should I do now or switch to another branch?

![image](https://github.com/Azure/iot-identity-service/assets/48575506/821ea968-715e-4c47-aec2-ac572fc99a61)

**Comment by Ming-Y-ANG** [comment]
I found that the problem was caused by docker directory mapping. The project path was mapped to /src in docker, but when the sub-repository was cloned, git saved the absolute path information of the host. Mapping the project source code path to the same path in the container can solve the problem：

![image](https://github.com/Azure/iot-identity-service/assets/48575506/ae64c18b-619e-4190-9a1c-af7b513ec200)
![image](https://github.com/Azure/iot-identity-service/assets/48575506/54b3ad7a-2e82-4974-acdb-862435128999)
Also need to modify ci/package.sh
