### ISSUE TITLE
Please provide builds for Debian 12 armhf & arm64

### ISSUE THREAD

**Issue by stefanb2** [Azure/iot-identity-service#557]
[Raspberry Pi 5](https://www.raspberrypi.com/products/raspberry-pi-5/) is coming soon. Along with its release [Raspi OS](https://github.com/RPi-Distro/pi-gen) will be rebased to Debian 12.

F.ex. [moby-engine](https://packages.microsoft.com/debian/12/prod/pool/main/m/moby-engine/) already supports this platform.

Please provide builds for Debian 12 armhf & arm64 and also push them to the [production package repository](https://packages.microsoft.com).

**Comment by arsing** [comment]
@bishal41 @damonbarry @yophilav FYI

**Comment by bishal41** [comment]
Hi @stefanb2 - this is already in our plan to support, and we have an internal tracking PBI for this. I don't have an exact ETA though on when we will release. I would suggest you keep an eye on this site--> https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4. I will close this but please feel free to ping if you have any further questions.
