### ISSUE TITLE
Request for permission to incorporate a Rust function from iot-identity-service to parsec-openssl-provider project

### ISSUE THREAD

**Issue by gowthamsk-arm** [Azure/iot-identity-service#586]
Hello Project Maintainers,

I hope this message finds you well. We are currently working on a project (Parsec openssl provider) that we intend to make open source under this [organization](https://github.com/parallaxsecond), licensed under Apache 2.0 and have identified a [Rust function](https://github.com/Azure/iot-identity-service/blob/1.4.7/key/aziot-key-openssl-engine/src/lib.rs#L98) from your project that would greatly benefit our efforts. Before proceeding, we want to ensure full compliance with licensing and copyright regulations. We request your permission to incorporate the specified Rust function into our project. We would be adding the specified function in a separate file, that preserves, on that file, your license and copyright information. We value open collaboration and respect intellectual property rights, and your approval would be pivotal in advancing our shared goals. If you agree, please let us know if you accept this proposed approach or if you have another preferred method.

Thank you for your consideration.

Best regards,
Parsec Team

**Comment by arsing** [comment]
Thanks for asking. That function as well as the rest of the code is licensed under MIT, so you don't need any additional permission, just need to follow the terms of the license.
