### ISSUE TITLE
Using idtype module seems to recreate the module identity in the cloud 

### ISSUE THREAD

**Issue by FinitelyFailed** [Azure/iot-identity-service#600]
Hi,

We are using azure identity services version 1.4.7:
```
# aziotctl --version
aziotctl 1.4.7
```

And azure device update 1.0.2:
```
# /usr/bin/AducIotAgent -v
1.0.2
```

We are trying to setup ADU to use a module identity. As we have our own service which also connection to the IoT Hub using AIS. If borth ADU and our own service are setup to be run as "device" they fight over which should use the IoT Hub device. So we have chosen to use ADU as a module identity.

So I have configured identity service like this:
```
# cat /etc/aziot/identityd/config.d/adu.toml      
[[principal]]
uid = 800
name = "DeviceUpdate"
idtype = ["module"]
```

Which seems to work.

We are using ADU to perform an A-B update of the device.
We have these partitions:
- rootA
- rootB
- data
- boot

We are running our OS on the rootA partition.
And saving our config for AIS on a data partition, so that the config is not lost during the update. The config contains the connection string for the device on the IoT hub.
The config which is used to setup ADU to use an Module Identity is located  in "/etc/aziot/identityd/config.d/adu.toml" in our OS (i.e. on both rootA and later rootB).

When ADU performs the update (with the help of swupdate) a new version of our OS is installed on rootB. And a flag is set on the boot partition, so that when a reboot is performed rootB is booted instead of rootA. Than it reboots.

After a reboot the command "aziotctl config apply -c /data/aziot/config.toml" is performed, so that AIS can connect to the device in the IoT Hub. 

Now to the problem after that command has been performed the Module Identity for our device in the IoT hub seems to be recreated. As nothing we put on the Module Identities twin remains. 

We need to be able to set tags on the Modules Identity twin and make them stick. One of the tags is which ADUGroup this device belongs to.

According to this [documentation](https://github.com/Azure/iot-identity-service/blob/main/docs-dev/running/aziot-identityd.md): "If the idtype contains module, the name will be used by the Identity Service to generate new cloud identities, if not created already.". It should work as we have a module identity with the same name, but after an update is performed the twin is missing our tags.

**Comment by gordonwang0** [comment]
Could you provide logs from the startup of aziot-identityd after the update? Those should show which modules identities are being modified.

Also, are you persisting /var/lib/aziot across updates? If not, aziot-identity-service will have an empty state after the update, which may cause it to think that certain module identities don't exist.

**Comment by FinitelyFailed** [comment]
> Could you provide logs from the startup of aziot-identityd after the update? Those should show which modules identities are being modified.
The log from aziot-identityd is this:
`Mar 20 10:19:41 raspberrypi4-64 systemd[1]: Started Azure IoT Identity Service.`

Is there a way to set it to verbose logging?

> Also, are you persisting /var/lib/aziot across updates? If not, aziot-identity-service will have an empty state after the update, which may cause it to think that certain module identities don't exist.

We do not persist /var/lib/aziot across updates.

If I do:
```
aziotctl system stop
systemctl stop deviceupdate-agent
rm /etc/aziot/identityd/config.d/00-super.toml
rm -rf /var/lib/aziot/identityd/*
rm -rf /var/lib/aziot/keyd/*
```

Add something to the Module Identity twin.
And run:
```
aziotctl system restart
systemctl start deviceupdate-agent
aziotctl config apply
```
The Module Identity is recreated and all the things I added is gone.

**Comment by gordonwang0** [comment]
You can use `aziotctl system set-log-level` to change the log level. I would expect more logs from identityd than just the "Started Azure IoT Identity Service" line.

You probably need to preserve /var/lib/aziot across updates so that aziot-identity-service maintains its state. That should prevent it from recreating the module identities when it restarts.

**Comment by FinitelyFailed** [comment]
> You can use `aziotctl system set-log-level` to change the log level. I would expect more logs from identityd than just the "Started Azure IoT Identity Service" line.
> 

Ok, I'll try that when I'm back at the office tomorrow. And get back to you.


> You probably need to preserve /var/lib/aziot across updates so that aziot-identity-service maintains its state. That should prevent it from recreating the module identities when it restarts.

What we probably want to do is to create the device in IoT Hub, and a Module Identity. Where the Module Identity has a known name and an ADUGroup on its tags. So that the deviceupdate-agent on the device, can use that Module Identity and the ADUGroup specified on the Module Identitys twin. But that is not possible, you think?

**Comment by FinitelyFailed** [comment]
But isn't this about iot-identity? As far as I understand deviceupdate-agent uses AIS to speak to the IoT hub. And it is a configuration of AIS that says that deviceupdate-agent shall be a module?

This is the AIS config for deviceupdate-agent (ADU):
```
# cat /etc/aziot/identityd/config.d/adu.toml 
[[principal]]
uid = 800
name = "DeviceUpdate"
idtype = ["module"]
```

I changed the log level to trace via aziotctl. And included the log as a file, as well as the log for deviceupdate-agent.
[deviceupdate-agent-logs.txt](https://github.com/Azure/iot-identity-service/files/14692016/deviceupdate-agent-logs.txt)
[aziot-identity-log.txt](https://github.com/Azure/iot-identity-service/files/14692017/aziot-identity-log.txt)

I can see that aziot-identity recreates the Module Identity, but I can't see a reason why.

**Comment by gordonwang0** [comment]
From the Identity Service logs, there's a line:
> Hub identity "DeviceUpdate" will be recreated

This happens when the identity is specified in configuration (as you have specified in adu.toml), but the identity isn't present in identityd's stored state. Identityd recreates the module to set the module identity key, as it cannot derive the key of a module not present in its stored state.

Therefore, it looks like you will need to persist everything under /var/lib/aziot across updates to prevent the module from being recreated.

**Comment by FinitelyFailed** [comment]
Thanks!

You should probably update the [documentation](https://github.com/Azure/iot-identity-service/blob/main/docs-dev/running/aziot-identityd.md). And point out that module identity may be recreated, if the current running instance of aziot-identityd didn't create the module identity. And that one should be aware that the module identity can be created and recreated. Because in our case we will probably need to create some kind of hook, trigger or similar to catch that the module identity is create. So that we can write tags and so on to its twin. We had hoped for that we only needed to create the module identity _once_ in the cloud and at the same time write properties to it, but that will not work.

> idtype (optional) is the identity type returned to that host process associated with the IoT Hub identity type being returned to that host process - it is an array containing module, device, or local. If idtype is not specified, the caller will be authorized to access all cloud identity resources (except those created by Identity Service for host processes). **If the idtype contains module, the name will be used by the Identity Service to generate new cloud identities, if not created already**. idtype with device is only used in special cases, when the host process needs to retrieve the provisioned device identity, instead of module identity.
